### ISSUE TITLE
jitsi-hammer doesn't send any rtp traffic

### ISSUE THREAD

**Issue by xtavras** [jitsi/jitsi-hammer#3]
Hi guys, I'm trying to make some stress tests on our new "jiisi-meet" server using jitsi-hammer, I'm starting it like this

```
./jitsi-hammer.sh -XMPPdomain example.com -XMPPhost example.com -MUCdomain conference.example.com  -users 20 -length 120 -audiortpdump resources/rtp_opus.rtpdump -videortpdump resources/rtp_vp8.rtpdump -summarystats 
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:961:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
service-unavailable(-1)

``` 

I can see all 20 users on server in prosody backend (c2s:show()), but I don't see any rtp traffic (with tcpdump or wireshark), jitsi-videobridge log is empty too. If I make a real session with web-cam and micro everything works fine.  I'm using example rtp files from git.

**Comment by bovenyan** [comment]
Same problem here. Could it be the problem with the ALSA lib?

**Comment by xtavras** [comment]
Hi @bovenyan,

I fixed this, but forget to mention here.
you need start a new jitsi-meet session in your browser and only after that start jitsi-hammer for the same room name (use "-room" option) without closing your browser. Don't bother with ALSA messages, it will actually work.

Best,
Stan

**Comment by bovenyan** [comment]
@xtavras ,
Thank you. I fixed it as well. My problem turns out that I'm using X11 forwarding. It therefore uses the local machine to run hammer while the local machine doesn't have ALSA. I installed pulseaudio and everything works fine right now.

Best,
boven

**Comment by Paultok** [comment]
Hi, I wanted to quickly test jitsi-hammer on meet.jitsi.org (the free jitsi meet service on internet), although it can successfully login in the room, it does not seem to send any video or audio. What I am doing wrong? (Also note the ICE failure). What can I do to test jitsi-hammer against meet.jitsi.org ?

./jitsi-hammer.sh -XMPPdomain meet.jitsi.org -XMPPhost meet.jitsi.org -MUCdomain conference.meet.jitsi.org -ivf resources/big-buck-bunny_trailer_track1_eng.ivf -room testnow
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connessione rifiutata (111)
bt_audio_service_open: connect() failed: Connessione rifiutata (111)
bt_audio_service_open: connect() failed: Connessione rifiutata (111)
bt_audio_service_open: connect() failed: Connessione rifiutata (111)
ALSA lib pcm_dmix.c:961:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
17:25:45.477 GRAVE: [23] org.jitsi.hammer.FakeUser.fatal() ICE failed for user Jitsi-Hammer_0. Agent state: Running

**Comment by tkd4444** [comment]
Hi Guys,

I'm having the same problem. I was able to compile jitsihammer. I can see the hammer users in the conference while I'm on the same conference via browser. But no traffic, no sound, no video.

These are the executing parameters:

`./jitsi-hammer.sh -BOSHuri https://domain_name.com/http-bind -ivf resources/big-buck-bunny_trailer_track1_eng.ivf -room siptest -users 3 -allstats`

From the logs there is this warning which could be relevant:

```
INFO: Gathering candidates for component muxed_stream.RTP. Local ufrag bee5l1bke6dj65
[WARNING] 
java.lang.IllegalArgumentException: minPort (0) and maxPort (50) should be integers between 1024 and 65535.
	at org.ice4j.ice.harvest.HostCandidateHarvester.checkPorts(HostCandidateHarvester.java:727)
	at org.ice4j.ice.harvest.HostCandidateHarvester.createDatagramSocket(HostCandidateHarvester.java:645)
	at org.ice4j.ice.harvest.HostCandidateHarvester.harvest(HostCandidateHarvester.java:367)
	at org.ice4j.ice.Agent.gatherCandidates(Agent.java:582)
	at org.ice4j.ice.Agent.createComponent(Agent.java:508)
	at org.ice4j.ice.Agent.createComponent(Agent.java:455)
	at org.jitsi.hammer.utils.IceMediaStreamGenerator.generateIceMediaStream(IceMediaStreamGenerator.java:151)
	at org.jitsi.hammer.FakeUser.acceptJingleSession(FakeUser.java:714)
	at org.jitsi.hammer.FakeUser.access$200(FakeUser.java:64)
	at org.jitsi.hammer.FakeUser$1.handleIQRequest(FakeUser.java:346)
	at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
iq request handler got jingle iq: <iq to='fbc69c7b-b792-4b96-8327-c731490d24be@domain_name.com/a28efd8f-a2ba-4bfb-b129-ab1262e039bc' from='siptest@conference.domain_name.com/34c3a827' id='ZmJjNjljN2ItYjc5Mi00Yjk2LTgzMjctYzczMTQ5MGQyNGJlQGhjaWNvbm5lY3QuaGVhbHRoY29hY2hpbnN0aXR1dGUuY29tL2EyOGVmZDhmLWEyYmEtNGJmYi1iMTI5LWFiMTI2MmUwMzliYwAzNDY2N2U4NS05MTBjLTRiNWQtYjQ0MS1mNzc1MWVmNjg1Y2Y6c2VuZElRALaCrsB0KM9HdShEdMuFN+8=' type='set'><jingle xmlns='urn:xmpp:jingle:1' action='transport-info' initiator='siptest@conference.domain_name.com/34c3a827' sid='b8e7d80e9649'><content creator='initiator' name='audio'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate type='host' protocol='udp' id='73v29tvzis' ip='192.168.0.94' component='1' port='51873' foundation='3933170122' generation='0' priority='2122260223' network='1'/></transport></content><content creator='initiator' name='video'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate type='host' protocol='udp' id='bondvlcesh' ip='192.168.0.94' component='1' port='59195' foundation='3933170122' generation='0' priority='2122260223' network='1'/></transport></content></jingle></iq>
iq request handler got jingle iq: <iq to='fbc69c7b-b792-4b96-8327-c731490d24be@domain_name.com/a28efd8f-a2ba-4bfb-b129-ab1262e039bc' from='siptest@conference.domain_name.com/34c3a827' id='ZmJjNjljN2ItYjc5Mi00Yjk2LTgzMjctYzczMTQ5MGQyNGJlQGhjaWNvbm5lY3QuaGVhbHRoY29hY2hpbnN0aXR1dGUuY29tL2EyOGVmZDhmLWEyYmEtNGJmYi1iMTI5LWFiMTI2MmUwMzliYwA5ZWFmOWM4Yi02MTA0LTRiZjMtOWE3NS0yNzdlZDdmYjA1MGE6c2VuZElRALaCrsB0KM9HdShEdMuFN+8=' type='set'><jingle xmlns='urn:xmpp:jingle:1' action='transport-info' initiator='siptest@conference.domain_name.com/34c3a827' sid='b8e7d80e9649'><content creator='initiator' name='audio'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate type='host' protocol='tcp' id='wx1wd1s36e' ip='192.168.0.94' component='1' port='9' foundation='2766968122' generation='0' network='1' priority='1518280447' tcptype='active'/></transport></content><content creator='initiator' name='video'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate type='host' protocol='tcp' id='kw3x75ys5w' ip='192.168.0.94' component='1' port='9' foundation='2766968122' generation='0' network='1' priority='1518280447' tcptype='active'/></transport></content></jingle></iq>
iq request handler got jingle iq: <iq to='fbc69c7b-b792-4b96-8327-c731490d24be@domain_name.com/a28efd8f-a2ba-4bfb-b129-ab1262e039bc' from='siptest@conference.domain_name.com/34c3a827' id='ZmJjNjljN2ItYjc5Mi00Yjk2LTgzMjctYzczMTQ5MGQyNGJlQGhjaWNvbm5lY3QuaGVhbHRoY29hY2hpbnN0aXR1dGUuY29tL2EyOGVmZDhmLWEyYmEtNGJmYi1iMTI5LWFiMTI2MmUwMzliYwAxZmI0MmZkMC1iMDcyLTQzYjMtODEyYi1lMzc1N2RkNGVhNWU6c2VuZElRALaCrsB0KM9HdShEdMuFN+8=' type='set'><jingle xmlns='urn:xmpp:jingle:1' action='transport-info' initiator='siptest@conference.domain_name.com/34c3a827' sid='b8e7d80e9649'><content creator='initiator' name='audio'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate rel-port='51873' type='srflx' protocol='udp' id='phfob7m4nw' ip='188.167.250.175' component='1' port='7621' foundation='478089246' generation='0' rel-addr='192.168.0.94' priority='1686052607' network='1'/></transport></content><content creator='initiator' name='video'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='kyaT' pwd='TeCqJAVeNFhT0bl8V7vMABxt'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256' required='true'>2C:09:1C:DE:9A:E9:1A:20:61:D5:50:05:12:EE:33:6F:15:92:DD:F6:70:ED:53:D8:67:FC:9B:19:00:CD:2F:2C</fingerprint><candidate rel-port='59195' type='srflx' protocol='udp' id='dkzc6rpvt5' ip='188.167.250.175' component='1' port='7613' foundation='478089246' generation='0' rel-addr='192.168.0.94' priority='1686052607' network='1'/></transport></content></jingle></iq>
```

Thank you !

**Comment by gurvinderdadyala** [comment]
@tkd4444 
Hi there, I am facing a similar issue. Are you able to make it work.

**Comment by tkd4444** [comment]
@gurvinderdadyala I have tried everything, no it's not working.

**Comment by gurvinderdadyala** [comment]
@tkd4444 Thank you for the info. I am still trying to make it run by trying different options.

**Comment by gurvinderdadyala** [comment]
@tkd4444 Use master build from this repo https://github.com/jernejt/jitsi-hammer
It works perfectly fine. He has submitted patches to main repo however they have not merged it yet So therefore go to this repo and clone from there.

**Comment by tkd4444** [comment]
@gurvinderdadyala thanks ! I'll try that.

**Comment by tkd4444** [comment]
@gurvinderdadyala can you see in the conference the actual video ? Or just the traffic ?

**Comment by gurvinderdadyala** [comment]
@tkd4444  No we could not get it fully working, It was showing load in server and bandwidth however video  was not rendering from dummy participants.

**Comment by sunilkumarmohanty** [comment]
Hi, 
I am able to see the audio and video thumbnails but when I click on the fake users, I cannot see them on the main screen. Moreover, the main screen goes completely blank.
